name: Main

on: workflow_dispatch

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gdrive]
          cd src
          pip install .

      - name: Reproduce and push
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          REPO_KEY: ${{ secrets.REPO_TOKEN }}
        run: |
          dvc pull
          dvc repro
          dvc push
          git add dvc.lock
          git commit 'Latest model and data version'
          git push origin