name: Main

on:
  push:
    branches:
    - main

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gdrive]
          cd src
          pip install .

      - name: Run experiment
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull
          dvc repro
          dvc push